name: Firebase Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy Firebase Functions
        if: ${{ github.event.pusher.name != 'dependabot[bot]' && github.event.head_commit.modified | contains('backend/') }}
        run: firebase deploy --only functions
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEMOCRASTYLE_A73D2 }}'
          projectId: democrastyle-a73d2

  deploy-hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy Firebase Hosting
        if: ${{ github.event.pusher.name != 'dependabot[bot]' && github.event.head_commit.modified | contains('frontend/') }}
        run: firebase deploy --only hosting
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEMOCRASTYLE_A73D2 }}'
          projectId: democrastyle-a73d2

